version: '2'
services:
  nvstreamer:
    image: nvcr.io/nvidia/jps/vst:1.3.0-24.08.1-aarch64
    user: "0:0"
    network_mode: "host"
    runtime: nvidia
    logging:
      driver: "json-file"
      options:
        max-size: "8192m"
        max-file: "3"
    container_name: nvstreamer
    entrypoint: sh -c '/opt/vst_release/launch_vst --debug-level 3 2>&1 | tee -a /opt/vst_release/webroot/log/vst.log'
    environment:
      ADAPTOR: streamer
    volumes:
      - ./config/nvstreamer/vst_config.json:/opt/vst_release/configs/vst_config.json
      - ./config/nvstreamer/vst_storage.json:/opt/vst_release/configs/vst_storage.json
      - /data/vst-volume:/opt/store
      - /usr/lib/aarch64-linux-gnu/nvidia/:/usr/lib/aarch64-linux-gnu/tegra/
    deploy:
      resources:
        limits:
          memory: 5600M
      restart_policy:
        condition: always


